
export const GET_WALLET_ADDRESS = "GET_WALLET_ADDRESS";
export const GET_USER_THB_BALANCE ="GET_USER_THB_BALANCE"
export const GET_USER_THB_LP_BALANCE ="GET_USER_THB_LP_BALANCE"
export const GET_USER_TAMOUNT ="GET_USER_TAMOUNT"
export const GET_USER_TAMOUNT_LP ="GET_USER_TAMOUNT_LP"
export const GET_USER_BRL ="GET_USER_BRL"
export const  GET_USER_BRL_LP ="GET_USER_BRL_LP"
export const GET_USER_MINT_BRAWL_POINTS ="GET_USER_MINT_BRAWL_POINTS"
export const GET_CURRENT_BP_TOKENS ="GET_CURRENT_BP_TOKENS"
export const GET_MAX_BP_TOKENS="GET_MAX_BP_TOKENS"
export const GET_ROAD_PRICE = "GET_ROAD_PRICE"
export const GET_ROAD_TOTALSUPPLY = "GET_ROAD_TOTALSUPPLY";
export const GET_PRESALE_HARD_CAP= "GET_PRESALE_HARD_CAP";
export const GET_PRESALE_SOFT_CAP ="GET_PRESALE_SOFT_CAP";
export const GET_MIN_PURCHASE ="GET_MIN_PURCHASE";
export const GET_MAX_PURCHASE ="GET_MAX_PURCHASE";
export const GET_TOTAL_SOLD_TOKENS ="GET_TOTAL_SOLD_TOKENS";
export const GET_START_TIME ="GET_START_TIME";
export const GET_END_TIME ="GET_END_TIME"

